[package]
name = "dlt-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "dlt"
path = "src/main.rs"

[dependencies]
clap = "4.3.10"
libdlt-sys = "0.1.1"

[build-dependencies]
bindgen = "0.65.1"
